### ISSUE TITLE
Script para criação das procedures

### ISSUE THREAD

**Issue by leonardoaguiar** [souzara/todoapp#1]
Poderia disponibilizar o script de criação das procedures?

**Comment by rzvieira** [comment]
Fala Leonardo!
Eu estava usando um banco de dados para testes. As procedures estão lá, se quiser pode usar.

Data Source=mssql5.gear.host;Initial Catalog=todoapp3; Persist Security Info=True; user id=todoapp3; password=Uh90U1hW4_?l;  MultipleActiveResultSets=true;

Abraços!

**Comment by souzara** [comment]
Leonardo, atualizei o script com as procedures,

Rafael, obrigado pelo apoio, aproveitei sua conexão pra exportar as procedures e atualizar o repositório.

Abraços

**Comment by leonardoaguiar** [comment]
Muito obrigado @souzara e @rzvieira
